### ISSUE TITLE
Incorrect names in search

### ISSUE THREAD

**Issue by christianbundy** [rogeriochaves/feedless#1]
Hi! This is such a great project, I love it. Thanks for sharing!

I found a small bug where if you do a search like:

https://feedless.social/search?query=mix

Then it shows some profiles, but the profiles names are wrong. I think what's happening is that someone is publishing an 'about' message to set a name for Mix's profile, but there's some code that's applying the name to *their* profile instead. When you go to their actual profile the name is correct, if that's helpful.

:star2:

**Comment by rogeriochaves** [comment]
Thank you very much! I'm glad you liked it!

You are absolutely correct, on the search I'm looking for all `about`s, not just the one by the author, I thought it could be good to give more results but you are right that it could have some not good consequences

**Comment by christianbundy** [comment]
I think what I'm seeing is the other way around. For example, if I post a message saying "I call Mix 'Mixo'" in the search results you see a link to **my** profile with **my** image and the name "Mixo".

**Comment by rogeriochaves** [comment]
sorry for the loong delay, I finally fixed this on df934a06ae97829f40ceb2744c5dc13b59bfc9f0
https://feedless.social/search?query=mix

tell me if something is still wrong :)
