### ISSUE TITLE
Run local, what secret is used,  multiple accounts?

### ISSUE THREAD

**Issue by zicmama** [rogeriochaves/feedless#4]
When creating my account, the secret I get on the web page is different from the one in ~/.social/secret ? This is normal? Now a cookie is used??
Is it possible to open multiple accounts?

**Comment by rogeriochaves** [comment]
Unfortunately yes, I focused more on the web version first where /secret is the pub secret and multiple people can sign in, using the cookie to hold the key, I still need to change it for the CLI version

**Comment by rogeriochaves** [comment]
Done in 65578bf1474e766b831608d2c2b3893bbb0c423a, 8938d8b2b57b4b24093e472c4c9947d2df72489b and aa81b9de8e7382efeb3dbbe9f5531577ec6f6ef3, now it no longer uses cookies for the standalone version, instead it uses the ~/.ssb folder and the `secret` file in there

It is still possible to logout and login with another account, what that does is replacing your `secrets` file. Also if you never had a ~/.ssb/secret file you go through the "account creation" flow for a better use experience

**Comment by zicmama** [comment]
Great! It will be kind if you add a Readme explaining different install (local or Pub) and behaviour.

**Comment by rogeriochaves** [comment]
@zicmama I added a Getting Started section on README, and there is also a development section for those who want to manually npm install. I'll close this for now, feel free to give more suggestions
