### ISSUE TITLE
Delay changing/refreshing "about"

### ISSUE THREAD

**Issue by zicmama** [rogeriochaves/feedless#7]
https://feedless.social/about is always keeping first init sentences...
Cannot change it.

**Comment by zicmama** [comment]
it was a propagation delay... Now it has changed.
It could be confusing

**Comment by rogeriochaves** [comment]
Thank for reporting, I had more reports of that as well and experienced the issue myself, I will work on a solution!

**Comment by rogeriochaves** [comment]
Fixed in 3f163a2f3f64ee864e172abeb06b9de647c20495
